### ISSUE TITLE
Skip running tests when the only file changed is markdown

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-tools#1667]
Take this PR for example: https://github.com/Azure/azure-sdk-for-js/pull/15523. 

All it does is update the date in the changelog before a release. All tests associated with that folder is run in the PR CI which adds no value. Is there a way for the PR CI to skip the tests the only files changed are markdown files? 

What I am looking for ways to reduce the wait time on PRs that are only trying to update markdown files. No issues in running the link verififcation and other checks.

(Not sure if other language repos have use for running the tests when markdown files are changed)

**Comment by ramya-rao-a** [comment]
Same for the yml files!! See https://github.com/Azure/azure-sdk-for-js/pull/15146

cc @praveenkuttappan, @chidozieononiwu

**Comment by kurtzeborn** [comment]
In the teams discussion about this, you (@benbp) proposed that we could have detection in the matrix generation that would inspect the changed files and generate an empty test matrix for folders/libraries where only .md or .yml files changed.

**Comment by benbp** [comment]
I was thinking about adding some sort of filtering to the matrix config, e.g. `GenerateOnFilesChanged` or something like that:

```
  - name: MatrixConfigs
    type: object
    default:
      - Name: Js_live_test_base
        Path: eng/pipelines/templates/stages/platform-matrix.json
        Selection: sparse
        GenerateVMJobs: true
        GenerateOnFilesChanged:
          - *.js
          - *.ts
          - *.json
          # and so on...seems brittle
```

The more that I think about it, it may be better to have this kind of logic be in its own step, which could include scripts for various kinds of skip/run hook inputs and outputs, e.g.:

```
# step generates some variable that can be used later on
- template: set_test_job_condition.yml
- template: archetype-sdk-tests-generate.yml
  parameters:
    Condition: variables['GENERATE_TESTS']

# in the generate job:
job:
  condition: eq(${{ parameters.Condition }}, true)

```
