### ISSUE TITLE
Pipeline Generator: Tests pipeline trigger overrides should target more branches

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#184]
We've had instances in the past where PRs targeting a branch that is not `master` in live tests are refused by the bot. These should follow a mapping like the one at: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/cosmos/ci.yml#L12

```
pr:
  branches:
    include:
    - master
    - feature/*
    - hotfix/*
    - release/*
    - restapi*
```

Because other settings are overridden these changes cannot happen in the `tests.yml` they must be part of the procedure that creates/updates pipelines.
