### ISSUE TITLE
[stress] Allow configurable docker build folders

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-tools#2569]
Currently the `stress-test-deployment-lib.ps1` assumes that the location of the Dockerfile is the same folder it should use as the build folder for the project.

This doesn't quite work for Go stress projects, which store their artifacts under `internal/stress`, since the Dockerfile is in a subfolder but to build the module we need to build from the root, which is two levels above the `stress` foler.

Talking with @benbp, we thought we could basically do two things:
1. Add annotations into `Chart.yaml` to specify some build parameters:
    Example: 
    ```yaml
      # in Chart.yaml
      annotations:
        dockerbuilddir: '../..'
        dockerfile: './Dockerfile'
    ```
2. Change the [stress-test-deployment-lib.ps1](https://github.com/Azure/azure-sdk-for-go/blob/52ad1c9e349078f275e121bab06202d1ea95924b/eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1#L163) file to read those annotations and use them when building the Docker image for the project.
