### ISSUE TITLE
[stress testing] chaos-mesh policies require specific host names and can't use wildcards

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-tools#2816]
chaos-mesh lets you add in network loss using a 'loss' policy. 

A typical chaos mesh policy looks like this:

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: ripark-network-attack-sb
  namespace: ripark
  labels: null
  annotations:
    experiment.chaos-mesh.org/pause: 'false'
spec:
  action: loss
  # <removing most stuff>
  externalTargets:
    - random1.servicebus.windows.net
    - random2.servicebus.windows.net
```

We previously tried to use a "wildcard" hostname by using the root domain (ex: servicebus.windows.net) but that doesn't work. Even with that enabled as the 'externalTarget' you can still access and work with hosts that are more specific (ex: mysb.servicebus.windows.net).

This means we need to update the the externalTargets to be the _actual_ generated hostnames (and probably also remove them when needed). We might want to consider doing a few things.

chaos-mesh does have an API, so programatically updating this shouldn't be too hard. We'd just need to establish a convention in our arm templates and probably output a few extra variables to signal which ones need to be added.
