### ISSUE TITLE
[Perf] Use sparse checkout in perf.yml

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-tools#3844]
File `/eng/common/pipelines/templates/jobs/perf.yml` should use `sparse-checkout.yml` (excluding test recordings) instead of the `checkout` task.  .NET clone times improve from 3m25s to 45s.

Example:

```
- template: /eng/common/pipelines/templates/steps/sparse-checkout.yml
  parameters:
    Paths:
    - '/*'
    - '!sdk/**/test-recordings/*'
    - '!sdk/**/recordings/*'
    - '!sdk/**/SessionRecords/*'
    - '!sdk/**/session-records/*'
    Repositories:
    - Name: $(Build.Repository.Name)
      Commitish: $(Build.SourceVersion)
      WorkingDirectory: $(System.DefaultWorkingDirectory)
    - Name: Azure/azure-sdk-tools
      Commitish: main
      WorkingDirectory: $(System.DefaultWorkingDirectory)/azure-sdk-tools
```
