### ISSUE TITLE
Perf Framework fails with packages at diffrent versions

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-tools#4452]
using this fragment 

- Service: keyvault-keys
  Languages:
    Cpp:
      Project: azure-security-keyvault-keys-perf
      PackageVersions:
      - azure-security-keyvault-keys-cpp: 4.2.0
      - azure-security-keyvault-keys-cpp: source
      - azure-identity-cpp: 1.3.0
      - azure-identity-cpp: source
  Tests:
  - Test: GetKey
    Arguments: 
    - -r 0
    TestNames:
      Cpp: GetKey

to run the getkey test throws exceptions in Program.cs line 164                             PackageVersions = p.Value.PackageVersions.Where(d =>
                                String.IsNullOrEmpty(options.PackageVersions) || Regex.IsMatch(d[p.Value.PrimaryPackage], options.PackageVersions)),

it is looking for keyvault keys with version 1.3.0

**Comment by mikeharder** [comment]
This is not the correct syntax to specify multiple packages.  You want to use something like this example:

```yml
PrimaryPackage: azure-storage-blob
PackageVersions:
- azure-core: 1.26.0
  azure-storage-blob: 12.14.0
- azure-core: source
  azure-storage-blob: source
```

https://github.com/Azure/azure-sdk-tools/blob/67cdc22c6102a116fe981dbf984bec72a2cdfb34/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml#L187-L192

You need to specify the `PrimaryPackage` (so the framework knows which package version to report in the results summary), and then each "group" of packages is expressed as a YML list.
