### ISSUE TITLE
[stress] Helm version check doesn't understand `~` in version strings

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-tools#4590]
Getting this error now:

```
/workspaces/_/eh-stress/sdk/messaging/azeventhubs/internal/eh/stress/Chart.yaml
Exception: /workspaces/_/eh-stress/eng/common/scripts/stress-testing/find-all-stress-packages.ps1:90:13
Line |
  90 |              throw "The stress-test-addons version in use for '$chartF …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The stress-test-addons version in use for
     | '/workspaces/_/eh-stress/sdk/messaging/azeventhubs/internal/eh/stress/Chart.yaml' is ~0.2.0, please use
     | versions >= 0.2.0
```

When my Chart.yaml has this:

```yaml
dependencies:
- name: stress-test-addons
  version: ~0.2.0
  repository: https://stresstestcharts.blob.core.windows.net/helm/
```

We should allow this as it makes it so we auto-upgrade (and will know when future upgrades break us). I'm not entirely sure how the check is done, but we'd want to use the same evaluation that helm does, or eliminate the check altogether if we don't need it anymore.
