### ISSUE TITLE
Automate OIDC enablement for github actions

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#5792]
Across our repositories we are planning on using github's OIDC with azure in order to avoid storing any credentials in github. This process should be somewhat automated and/or config based. See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect for more details.

Rough steps to set this up manually, e.g. for access to a keyvault (the role assignment role and scope determine the access):

```
az ad app create --display-name <app name>
az ad sp create --id <app id>

az role assignment create --role "Key Vault Secrets User" --subscription <subscription> --assignee-object-id  <sp oid> --assignee-principal-type ServicePrincipal --scope /subscriptions/<subscription>/resourceGroups/<secrets resource group>/providers/Microsoft.KeyVault/vaults/<keyvault name>

az rest --method POST --uri "https://graph.microsoft.com/beta/applications/<app oid>/federatedIdentityCredentials" --body '{"name":"<cred name>","issuer":"https://token.actions.githubusercontent.com","subject":"repo:<repository e.g. azure/azure-sdk-tools>:ref:refs/heads/main","description":"OIDC for main","audiences":["api://AzureADTokenExchange"]}'
```

Then add secrets to the github repository via Settings -> Security/Secrets and Variables -> Actions -> New Repository Secret. Add `AZURE_CLIENT_ID` (equals the service principle app id from above), `AZURE_SUBSCRIPTION_ID` and `AZURE_TENANT_ID` as secrets, though the values themselves are not sensitive.

From there, you can log in to az in the github workflow and consume the secrets. Due to the above scoping from the `az rest` call this will only be authorized running in the main branch. You can also scope by job_workflow_ref or environment (and add the secrets to a github environment instead) if branch scoping isn't desired:

```
- name: 'Az CLI login'
  if: ${{ github.event_name == 'issues' && github.event.action == 'opened' }}
  uses: azure/login@v1
  with:
    client-id: ${{ secrets.AZURE_CLIENT_ID }}
    tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
```

Related to https://github.com/Azure/azure-sdk-tools/issues/5789
