### ISSUE TITLE
Update all our repository references to include a ref

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#659]
In our pipelines we have a lot of yml files that look like:
```
resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure
    - repository: azure-sdk-build-tools
      type: git
      name: internal/azure-sdk-build-tools
```

While that works it always pulls the latest version from the master branch. This causes trouble when we are trying to do a build for an older commit in the repo for a hotfix build or other branches that aren't on tip. Instead we need to add an explicit `ref:` to each [repository reference](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#repository-resource) across all our repositories. This along with the work @chidozieononiwu has done to enable tagging of our tools repo should enable us to use a ref to a tag in all yml files in our repos. 

So I think we have the following work:
- [x] Add ref's to all existing repository references in all yml files in all language repos.
  - [x] Extend tool to other repos (c, cpp, android, go, ios)
- [x] Add documentation in our contributing md files in our tools repo that instruct folks how to produce a build with a tag that they can use to update the ref as needed.
- [x] We should implement automation that when we tag a tools repo we also submit a PR to all our language repo's that update the ref's to the latest tag after validation.
- [x] Once we have all our master repo's updated with ref's and we have done a release cycle we should go in and clean-up all old files left in our master repo of both tools repos (azure-sdk-tools and azure-sdk-build-tools). 
- [x] We should implement a validation check that ensures we have no repository references that doesn't contain a ref. This could be included as part of our automation to update the refs. 
- [ ] Move Repos list into central location
