### ISSUE TITLE
[PR Workflow] Add `TypeSpec` label if appropriate files are changed

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#7353]
As in title. We need this for several reasons, including:

- https://github.com/Azure/azure-sdk-tools/issues/7216
- https://github.com/Azure/azure-sdk-tools/issues/7352

Implementation-wise, we want to implement this in openapi-alps PR summary task ([recent example PR touching relevant code files](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/513409)), following rules as expressed in this PR:
- https://github.com/Azure/azure-rest-api-specs/pull/26542/files#diff-fc796b019795da5d3269d452fcdb1827ca9c8789a41f2e2dc1551f70b8f36878

``` yaml
description:
- if:
  - payloadType: Pull_Request
  then:
  - if:
    - filesMatchPattern: # any files, not necessarily all
        pattern: specification/.*(\.tsp|tspconfig.yaml)
    then:
    - addLabel:
        label: TypeSpec
```

Note that the above-given PR doesn't work as expected because the `filesMatchPattern` selector requires for **all** files to match the pattern [1]. We want to ad the label when **any** files match the pattern. 

One situation to consider is: what if given PR has both OpenAPI specs created by hand, and also generated from TypeSpec? In such case we also add the `TypeSpec` label. The assumption here is that such cases should be very rare and can be handled manually, while automation can approximate such PR to being TypeSpec-only PRs.

Related work:
- https://github.com/Azure/azure-sdk-tools/issues/5917

[1]:  
[source of `filesMatchPattern`](https://github.com/1ES-microsoft/GitOps.PullRequestIssueManagement/blob/5ae10f7e91bd248baf669027fbdc645db6b5e47c/src/GitOps.PullRequestIssueManagement.Core/Primitives/Data/Conditions/FilesMatchPatternCondition.cs)  
[doc for `filesMatchPattern`](https://eng.ms/docs/more/github-inside-microsoft/policies/resource-management?tabs=event-conditions)
