### ISSUE TITLE
Stress test matrix: name is too long

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-tools#7590]
I'm playing with the following matrix:
```yaml
matrix:
  sizeBytes:
    - "1024"
    - "16777216"
    - "52428800"
  parallel:
    - 100
  durationMin:
    - 15
  imageBuildDir:
    - "../../.."
  faults:
    - true
  scenarios:
    download-file:
      testScenario: downloadtofile
      sync: true

    download-file-async:
      testScenario: downloadtofile
      sync: false
```

Generated matrix looks good:

```json
Generated matrix for C:\repo\azure-sdk-for-java\sdk\storage\azure-storage-blob-stress\scenarios-matrix.yaml
{
  "job_1024_100_15_True_downloadfile": {
    "sizeBytes": "1024",
    "parallel": 100,
    "durationMin": 15,
    "imageBuildDir": "../../..",
    "faults": true,
    "testScenario": "downloadtofile",
    "sync": true
  },
  "job_1024_100_15_True_downloadfileasync": {
    "sizeBytes": "1024",
    "parallel": 100,
    "durationMin": 15,
    "imageBuildDir": "../../..",
    "faults": true,
    "testScenario": "downloadtofile",
    "sync": false
  },
  "job_16777216_100_15_True_downloadfile": {
    "sizeBytes": "16777216",
    "parallel": 100,
    "durationMin": 15,
    "imageBuildDir": "../../..",
    "faults": true,
    "testScenario": "downloadtofile",
    "sync": true
  },
  "job_16777216_100_15_True_downloadfileasync": {
    "sizeBytes": "16777216",
    "parallel": 100,
    "durationMin": 15,
    "imageBuildDir": "../../..",
    "faults": true,
    "testScenario": "downloadtofile",
    "sync": false
  },
  "job_52428800_100_15_True_downloadfile": {
    "sizeBytes": "52428800",
    "parallel": 100,
    "durationMin": 15,
    "imageBuildDir": "../../..",
    "faults": true,
    "testScenario": "downloadtofile",
    "sync": true
  },
  "job_52428800_100_15_True_downloadfileasync": {
    "sizeBytes": "52428800",
    "parallel": 100,
    "durationMin": 15,
    "imageBuildDir": "../../..",
    "faults": true,
    "testScenario": "downloadtofile",
    "sync": false
  }
}
```

But then  helm/k8s are not happy about job names being too long:

Error: UPGRADE FAILED: failed to create resource: Job.batch "job-1024-100-15-true-downloadfileasync-java-blobstorage-31" is invalid: [metadata.labels: Invalid value: "limolkova-job-1024-100-15-true-downloadfileasync-java-blobstorage-31": must be no more than 63 characters, spec.template.spec.volumes[0].name: Invalid value: "test-env-job-1024-100-15-true-downloadfileasync-java-blobstorage-31": must be no more than 63 characters, spec.template.spec.containers[1].volumeMounts[0].name: Not found: "test-env-job-1024-100-15-true-downloadfileasync-java-blobstorage-31", spec.template.spec.initContainers[0].volumeMounts[0].name: Not found: "test-env-job-1024-100-15-true-downloadfileasync-java-blobstorage-31", spec.template.spec.initContainers[1].volumeMounts[1].name: Not found: "test-env-job-1024-100-15-true-downloadfileasync-java-blobstorage-31"]

Command 'helm upgrade java-blobstorage C:\repo\azure-sdk-for-java\sdk\storage\azure-storage-blob-stress -n limolkova --install --values C:\repo\azure-sdk-for-java\sdk\storage\azure-storage-blob-stress\generatedValues.yaml --set stress-test-addons.env=pg --set GitCommit=9a8a16a1e02c9dbccba076b964d9b26efbb76492' failed with code: 1

**Comment by benbp** [comment]
@lmolkova the helm release name is a hard limit. We can try to cut and randomize the suffix but I think updating the config a little bit will produce more useful test names:

```
displayNames:
  16777216: "16mb"
  52428800: "50mb"
  1024: "1mb"
  100: ""
  15: ""
  True: "faults"
  False: "nofaults"
matrix:
  scenarios:
    download-file:
      testScenario: downloadtofile
      sync: true

    download-file-async:
      testScenario: downloadtofile
      sync: false

  sizeBytes:
    - "1024"
    - "16777216"
    - "52428800"
  parallel:
    - 100
  durationMin:
    - 15
  imageBuildDir:
    - "../../.."
  faults:
    - true
```

Outputs

```
{
  "downloadfile_1mb_faults": {
    "testScenario": "downloadtofile",
    "sync": true,
    "sizeBytes": "1024",
    "parallel": 100,
    "durationMin": 15,
    "imageBuildDir": "../../..",
    "faults": true
  },
  "downloadfileasync_16mb_faults": {
    "testScenario": "downloadtofile",
    "sync": false,
    "sizeBytes": "16777216",
    "parallel": 100,
    "durationMin": 15,
    "imageBuildDir": "../../..",
    "faults": true
  },
  "downloadfile_50mb_faults": {
    "testScenario": "downloadtofile",
    "sync": true,
    "sizeBytes": "52428800",
    "parallel": 100,
    "durationMin": 15,
    "imageBuildDir": "../../..",
    "faults": true
  }
}
```
