### ISSUE TITLE
Prototype OneES Pipeline for `azure-sdk-for-python`

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#7647]
1. Run the tool [here](https://github.com/Azure/azure-sdk-tools/tree/benbp/pipeline-template-converter/tools/pipeline-template) against our stage yml.
   -  [OneES Wiki covering the effort](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/overview)
3. Ensure that all `stages` are replaced by the tool
4. Ensure that all `publishpipelineartifact` steps are replaced by the generic OneES one

Concern, we will need to change the selected `pool`, can we change the pool in place?

[Here is a commit](https://github.com/Azure/azure-sdk-for-net/commit/b4f1bfda273820fa385c5a98ca247c6dd3c22832)

**Comment by benbp** [comment]
Running task list (will edit):

- [ ] Auto-add @self to template references in stage template files
- [ ] See if we can fix ordering (so variables goes above jobs), but without having to declare inner types for everything (otherwise we could use the order attribute in yamldotnet)

**Comment by scbedd** [comment]
- [ ] `pipeline` mode follows `template` references and also runs update logic on each.

**Comment by scbedd** [comment]
- [ ] Identify issue with `eng/common/pipelines/templates/steps/publish-artifact.yml`, the tool entirely deletes the content.

**Comment by scbedd** [comment]
[This is my gist for processing template trees, versus individual yaml files](https://gist.github.com/scbedd/9569b0b8c4035516ca25256c15a3d2bf)

**Comment by scbedd** [comment]
`Pool` and `OsVmImage` being passed as parameters are actively ignored by the `archetype-sdk-tests-generate.yml`.

Needed to update the defaults on the yml itself to make it work.

**Comment by scbedd** [comment]
Somehow `'` is getting inserted after random `parameters` calls. I'm not certain if this is personal error or the tools doing. It's happened twice now which is definitely weird for me.

**Comment by scbedd** [comment]
> `Pool` and `OsVmImage` being passed as parameters are actively ignored by the `archetype-sdk-tests-generate.yml`.
> 
> Needed to update the defaults on the yml itself to make it work.

We cannot pass `OS` through as a variable. it needs to be hardcoded in parameters.

**Comment by scbedd** [comment]
This is the proper `sdl` to get passing injected `SDL` job

```
      sdl:
        sourceAnalysisPool:
          name: azsdk-pool-mms-win-2022-1es-pt
          image: azsdk-pool-mms-win-2022-1espt
          os: windows
        eslint:
          enabled: false
          justificationForDisabling: "ESLint injected task has failures because it uses an old version of mkdirp. We should not fail for tools not controlled by the repo. See: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3499746&"
        codeql:
          compiled:
            enabled: false
            justificationForDisabling: "CodeQL times our pipelines out by running for 2+ hours before being force canceled."
        psscriptanalyzer:
          enabled: true
          break: true
        policy: M365
        credscan:
          suppressionsFile: '$(Build.SourcesDirectory)/eng/CredScanSuppression.json'
          scanFolder: '$(Build.SourcesDirectory)/credscan.tsv'
          toolVersion: '2.3.12.23'
          baselineFiles: $(Build.SourcesDirectory)/eng/python.gdnbaselines
```
