### ISSUE TITLE
Clarify the process for the new-rp-namespace labels in the specs repo

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#8362]
With [PR](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/552463) the labels `new-rp-namespace-Approved` and `new-rp-namespace` were introduced.

The guidance for the user currently says: "once reviewed and approved by the Azure SDK team, ensure this PR has `new-rp-namespace-Approved` label". The wording could be changed to say `provide the link of the GitHub issue with the namespace approval and add the label ...` .

There has been confusion from the ARM reviewers and from the users on what to do in PRs when the label is requested.

Also, I am curious how this process started? Eng experience wasn't notified and neither the PM that manages the process @ronniegeraghty .

FYI @ladonnaq

**Comment by konrad-jamrozik** [comment]
Hey, sorry, I caused some confusion by adding this label recently. Previously, before my recent changes, the source said the following in [comment.yml](https://github.com/Azure/azure-rest-api-specs/blob/95381430ee109af5d02330184c2dc69f8ab31d38/.github/comment.yml):

``` yaml
- rule:
    type: label
    label: new-rp-namespace
    onLabeledComments: "Hi, @${PRAuthor}, our workflow has detected that there is no management SDK ever released for your RP, to further process SDK onboard for your RP, you should have the SDK client library name of your RP reviewed and approved. </br> <b>Action Required</b>: <li> Follow this guidance [Naming for new initial management or client libraries (new SDKs) - Overview (azure.com)](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/821/Naming-for-new-initial-management-or-client-libraries-(new-SDKs)) to create an issue for management client library name arch board review. </li> <li>Paste the issue link that you created in step 1 in this PR</li> </br> <b> Impact</b>: SDK release owner will take the approved management client library name to release SDK. No client library name approval will leads to SDK release delayed."
```

Here it is pretty-printed:

> Hi, @${PRAuthor}, our workflow has detected that there is no management SDK ever released for your RP, to further process SDK onboard for your RP, you should have the SDK client library name of your RP reviewed and approved. 
> 
> **Action Required**:
> 
> Follow this guidance [Naming for new initial management or client libraries (new SDKs) - Overview (azure.com)](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/821/Naming-for-new-initial-management-or-client-libraries-(new-SDKs)) to create an issue for management client library name arch board review. 
> 
> Paste the issue link that you created in step 1 in this PR
> 
> **Impact**: SDK release owner will take the approved management client library name to release SDK. No client library name approval will leads to SDK release delayed.


I have migrated this logic to `openapi-alps` in this PR, also adding the `new-rp-namespace-Approved` label requirement:

[Pull Request 552463](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/552463): In preparation for `workflow-bot` deletion: migrate rules `Approved-OkToMerge`, `ArcReview` and `new-rp-namespace`
