### ISSUE TITLE
[tsp-client] tspconfig.yaml import-not-found error

### ISSUE THREAD

**Issue by Alancere** [Azure/azure-sdk-tools#8583]
Add additionalDirectories to the current [tspconfig.yaml](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/azurestackhci/AzureStackHCI.StackHCIVM.Management/tspconfig.yaml)
``` yaml
parameters:
  dependencies:
    additionalDirectories:
      - specification/azurestackhci/Operations.Management
    default: ""
```

error:
![image](https://github.com/Azure/azure-sdk-tools/assets/46921893/96a301b7-374c-4c00-8971-844de8eb8109)

TempTypeSpecFiles:
![image](https://github.com/Azure/azure-sdk-tools/assets/46921893/e7d2a76a-7914-4b97-b176-396739acd67f)
