### ISSUE TITLE
Support Adding Approvers in suppressions.yaml for TypeSpecValidation(TSV)

### ISSUE THREAD

**Issue by wanlwanl** [Azure/azure-sdk-tools#9583]
Assign some approvers for a TSV rule. Only these approvers can approve the changes that suppress the TSV by `suppressions.yaml` [sample](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/maps/suppressions.yaml).

``` yaml
- tool: TypeSpecValidation
  path: /path/to/your/tspconfig.yaml
  rule: tspconfig-js-data-plane-rest-level-client-requirements
```

I'm wondering:
1. can or should we support this feature?
2. how to support it: add a label to block, remove to make PR mergable?
